config/routes.rb
Rails.application.routes.draw do
 resources :songs
 resources :users, only: [:new, :show, :create]
 root 'songs#index'

 get     '/login', to: "sessions#new"
 post    '/login', to: "sessions#create"
 delete '/logout', to: "sessions#destroy"

 delete '/delete_all', to: "songs#all" 

end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :songs

  validates :username, presence: true, uniqueness: true
  validates :name, :password, presence: true

  has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(username: params[:session][:username])

    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user
    else
      flash[:errors] = "Invalid login"
      render :new
    end

  end

  def destroy
    session.clear
    flash[:notice] = "Successful logout"
    redirect_to login_path
  end

  private

  def session_params
    params.require(:session).permit(:username, :password)
  end

end

app/controllers/song.rb
class Song < ActiveRecord::Base
  validates :title, :artist, presence: true
  # def to_param
  #   title
  # end

end

app/controllers/songs_controller.rb
class SongsController < ApplicationController

  def index
    session[:hits] ||= 0
    session[:hits] += 1
    @songs = current_user.songs.all
  end

  def show
    @song = current_user.songs.find(params[:id])
  end

  def new
    @song = current_user.songs.new
  end

  def create
    @song = current_user.songs.new(song_params)
    if @song.save
      redirect_to user_path(current_user)
    else
      flash[:errors] = @song.errors.full_messages.join(', ')
      render :new
    end
  end

  def edit
    @song = current_user.songs.find(params[:id])
  end

  def update
    @song = current_user.songs.find(params[:id])
    if @song.update(song_params)
      redirect_to user_path(current_user)
    else
      flash[:errors] = @song.errors.full_messages.join(', ')
      render :edit
    end
  end

  def destroy
    @song = current_user.songs.find(params[:id])
    @song.destroy
    redirect_to user_path(current_user)
  end

  def all
    current_user.songs.each do |song|
      song.destroy
    end
    flash[:notice] = "All crappy music is gone"
    redirect_to user_path(current_user)
  end

  private

  def song_params
    params.require(:song).permit(:title, :artist)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to @user
    else
      flash[:error] = @user.errors.full_messages.join(', ')
      render :new
    end
  end

  def show
    @songs = current_user.songs.all
  end

  private

  def user_params
    params.require(:user).permit(:name, :username, :password, :password_confirmation)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MyJams</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<nav>
  <%= button_to "Logout", logout_path, method: :delete %>
</nav>
<% flash.each do |key, value| %>
<%= content_tag :div, value, id: "flash_#{value}" %>
<% end %>

<%= yield %>

</body>
</html>

app/views/songs/_form.html.erb
<%= form_for(@song) do |f| %>
  <%= f.text_field :title, placeholder: "Baby, baby, baby, ooooooooh" %>
  <%= f.text_area :artist, placeholder: "Sir Mix-a-lot" %>
  <%= f.submit %>
<% end %>

app/views/songs/edit.html.erb
<%= render partial: 'form' %>

app/views/songs/index.html.erb
<%= link_to "Create a new song!", new_song_path, class: "new_song_link" %>

<h1> <%= session[:hits] %></h1>

<% @songs.each do |song| %>

<h3><%= link_to song.title, song_path(song), id: "song" %></h3>

<% end %>

app/views/songs/new.html.erb
<%= render partial: 'form' %>

app/views/songs/show.html.erb
<h1><%= @song.title %></h1>
<h1><%= @song.artist %></h1>
<%= link_to "Edit", edit_song_path(@song)%>
<%= link_to "Delete", song_path(@song), method: :delete %>

app/views/users/new.html.erb
<%= form_for(@user) do |f| %>
  <p>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :username %>
    <%= f.text_field :username %>
  </p>
  <p>
    <%= f.label :password %>
    <%= f.password_field :password %>
  </p>
  <p>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </p>
  <p>
    <%= f.submit "Create Account" %>
  </p>
<% end %>

app/views/users/show.html.erb
<h2> Welcome <%= current_user.name %> </h2>

<h3> <%= current_user.name %>'s Playlist </h3>

<% @songs.each do |song| %>
  <p>
    <%= song.title %>
    <%= button_to "Edit", edit_song_path(song), method: :get %>
    <%= button_to "Delete", song_path(song), method: :delete %>
  </p>
  <p>
    <%= song.artist %>
  </p>
<% end %>

<%= button_to "Add song", new_song_path, method: :get %>
<%= button_to "Delete all", delete_all_path, method: :delete %>